// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXr-fg1ppiLDZGMH4TGJJ1tx-S0zc-yI8',
    appId: '1:276979364524:web:d55c0cdedb18defaef6509',
    messagingSenderId: '276979364524',
    projectId: 'smartapp-608d4',
    authDomain: 'smartapp-608d4.firebaseapp.com',
    storageBucket: 'smartapp-608d4.firebasestorage.app',
    measurementId: 'G-ZRVYKNPJK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc25wVnzO_teb4sR62-1XX8sYA7ck_QzU',
    appId: '1:276979364524:android:4790a34f79744a76ef6509',
    messagingSenderId: '276979364524',
    projectId: 'smartapp-608d4',
    storageBucket: 'smartapp-608d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDo_4Zss9WexeJRk6r1n3a5VxI2YtF2rc',
    appId: '1:276979364524:ios:877b8242e820c8dfef6509',
    messagingSenderId: '276979364524',
    projectId: 'smartapp-608d4',
    storageBucket: 'smartapp-608d4.firebasestorage.app',
    iosBundleId: 'KHAIRATMouhcine.smaterAppAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDo_4Zss9WexeJRk6r1n3a5VxI2YtF2rc',
    appId: '1:276979364524:ios:877b8242e820c8dfef6509',
    messagingSenderId: '276979364524',
    projectId: 'smartapp-608d4',
    storageBucket: 'smartapp-608d4.firebasestorage.app',
    iosBundleId: 'KHAIRATMouhcine.smaterAppAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXr-fg1ppiLDZGMH4TGJJ1tx-S0zc-yI8',
    appId: '1:276979364524:web:3a65f87d6291264cef6509',
    messagingSenderId: '276979364524',
    projectId: 'smartapp-608d4',
    authDomain: 'smartapp-608d4.firebaseapp.com',
    storageBucket: 'smartapp-608d4.firebasestorage.app',
    measurementId: 'G-V5B7CCRR2R',
  );
}
